// flow-typed signature: 10fc7c441462320df60f9fb6534605cd
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-object-super_v^6.24.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-object-super'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-object-super' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-object-super/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-object-super/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-object-super/lib/index'>;
}
