// flow-typed signature: fb0f1f586fee037c6a0902c657209109
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-literals_v^6.22.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-literals/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-literals/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-literals/lib/index'>;
}
