// flow-typed signature: 514fac87a8d57f0c5ba31d52ccb9f4ee
// flow-typed version: <<STUB>>/es3ify_v^0.2.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es3ify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es3ify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es3ify/spec/es3ifyspec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es3ify/index' {
  declare module.exports: $Exports<'es3ify'>;
}
declare module 'es3ify/index.js' {
  declare module.exports: $Exports<'es3ify'>;
}
declare module 'es3ify/spec/es3ifyspec.js' {
  declare module.exports: $Exports<'es3ify/spec/es3ifyspec'>;
}
