// flow-typed signature: d5cdc7a70fa9a88e073285b7f7bf127d
// flow-typed version: <<STUB>>/flux-standard-action_v^2.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flux-standard-action'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flux-standard-action' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flux-standard-action/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flux-standard-action/lib/index.js' {
  declare module.exports: $Exports<'flux-standard-action/lib/index'>;
}
